import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/nav";
import { Suspense } from "react";
import ProgressBar from "@/components/progress";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />

        <Suspense fallback={<></>}>
          <ProgressBar height="3.2px" color="#f97316" shallowRouting />
        </Suspense>

        {children}

        <Toaster />
      </body>
    </html>
  );
}
